- name: Update package using YUM
  yum:
    name: '*'
    state: latest 

- name: Install nfs-utils package
  yum:
    name: nfs-utils
    state: present

- name: Create directory /mnt/external
  file:
    path: /mnt/external
    state: directory
    mode: '0755'

- name: Run the psql command to CREATE ROLE
  command: >
    /opt/phantom/bin/phenv psql postgresql://postgres:splunk3du@terraform-20230829010559018600000004.cxab3r5epwgv.us-east-1.rds.amazonaws.com:5432/phantom
    --echo-all
    --command "CREATE ROLE pgbouncer WITH PASSWORD 'splunk3du' login;"
  ignore_errors: yes

- name: Run the psql command to Grant  ROLE superuser
  command: >
    /opt/phantom/bin/phenv psql postgresql://postgres:splunk3du@terraform-20230829010559018600000004.cxab3r5epwgv.us-east-1.rds.amazonaws.com:5432/phantom
    --echo-all
    --command "GRANT rds_superuser TO pgbouncer;"
  ignore_errors: yes

- name: Mount NFS Share
  command: >
    mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 10.0.1.98:/ /mnt/external
  ignore_errors: yes

- name: Backup apps directory
  command: rsync -avz /opt/phantom/apps /mnt/external/
  
- name: Backup app_states directory
  command: rsync -avz /opt/phantom/local_data/app_states /mnt/external/
  
- name: Backup scm directory
  command: rsync -avz /opt/phantom/scm /mnt/external/
  
- name: Backup shared directory
  command: rsync -avz /opt/phantom/tmp/shared /mnt/external/
  
- name: Backup vault directory
  command: rsync -avz /opt/phantom/vault /mnt/external/

- name: Unmount /mnt/external
  command: umount /mnt/external
