---
- hosts: all
  become: true
  pre_tasks:

  - name: update YUM Repository index
    yum:
      update_cache: yes

- hosts: master_servers
  become: true
  roles:
    - master_servers

- hosts: splunk_servers
  become: true
  roles:
    - splunk_servers

- hosts: soar_servers
  become: true
  roles:
    - soar_servers

